apiVersion: apps/v1
kind: Deployment
metadata:
  name: v1-stx-app
  label:
    app: stx-app
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stx-app
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: stx-app
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: hello-starlingx
          image: docker.io/library/hello-world:linux
          ports:
           - containerPort: 80
             protocol: TCP
