apiVersion: v1
kind: Service
metadata:
  name: v1-stx-app
  label:
    app: stx-app
    release: {{ .Release.Name }}
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: stx-app
    release: {{ .Release.Name }}

